#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

path=(
  /usr/local/{bin,sbin}
  $(/usr/local/bin/brew --prefix coreutils)/libexec/gnubin
  $path
  ./node_modules/.bin
  /usr/local/share/npm/bin
  /usr/local/opt/ruby/bin
  $HOME/bin
  $JAVA_HOME/bin
  $HOME/.rvm/bin
)



export EDITOR=vim

export GITCLICK_STORAGE_PATH=~/Dropbox/.sync/gitclick/.gitclick
