function loadScript() {
  scriptPath=$1
  if [[ -s "${scriptPath}" ]]; then
    source "${scriptPath}"
  fi
}

export NVM_DIR="/Users/josa/.nvm"
local BREW_PREFIX=$(brew --prefix)

loadScript "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
loadScript "${NVM_DIR}/nvm.sh"
loadScript "${HOME}/.iterm2_shell_integration.zsh"
loadScript "${BREW_PREFIX}/etc/profile.d/z.sh"
loadScript "${BREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
loadScript "${BREW_PREFIX}/opt/zsh-history-substring-search/zsh-history-substring-search.zsh"

zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

fpath=(/usr/local/share/zsh-completions $fpath)

setopt rmstarsilent
setopt clobber

# Disable damm autocorrection
unsetopt CORRECT

unalias rm

alias ..="cd .."
alias ...="cd ../.."

alias g="git"
alias g="git"
alias gc="git commit -m"
alias e="ember"
alias a="atom"

alias cask="brew cask"

alias b="brew"
alias bs="brew search"
alias bi="brew install"
alias bh="brew home"
alias c="brew cask"
alias cs="brew cask search"
alias ci="brew cask install"
alias ch="brew cask home"

alias ls="ls -G"
alias ll="ls -l"
alias la="ls -la"

alias grep="grep --color='auto'"
alias ghist="history | grep"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
alias rm-empty-dirs="find . -type d -empty -delete"
alias git-cleanup-dirs="find . -type f -name '*.DS_Store' -ls -delete; find . -type d -empty -delete"

# Quicklook
alias ql='qlmanage -p "$@" >& /dev/null'

# Get readable list of network IPs
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print \$1'"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"

git-rm-gitkeep() {
  if [ $# -eq "0" ]; then
      DIR=$(pwd)
  else
      DIR=$1
  fi

  cd "$DIR" || return 1

  for line in $(git ls-files | grep '/.gitkeep$'); do
    EXTRA_FILES=$(git ls-files $(dirname "$line") | wc -l)
    if [ $EXTRA_FILES -ne "1" ]; then
      rm "$line"
    fi
  done
}

p() {
  local proj=$(ls ~/projects | fzf --query="$*" --select-1);
  if [[ "$proj" != "" ]]; then
    cd "$HOME/projects/$proj" || exit 1
  fi
};

pe() {
  local proj=$(ls ~/projects | fzf --query="$*");
  if [[ "$proj" != "" ]]; then
    cd "$HOME/projects/$proj" || exit 1
    atom .
  fi
};



man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}

function bman {
  man "${1}" | man2html > "/tmp/${1}.html"
  open -a "Google Chrome" "/tmp/${1}.html"
}
