# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/opt/zsh-history-substring-search/zsh-history-substring-search.zsh

zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

fpath=(/usr/local/share/zsh-completions $fpath)

setopt rmstarsilent
setopt clobber

# Disable damm autocorrection
unsetopt CORRECT

unalias rm


alias ..="cd .."
alias ...="cd ../.."

alias g="git"

alias b="brew"
alias cask="brew cask"

alias ls="ls -G"
alias ll="ls -l"
alias la="ls -la"

alias grep="grep --color='auto'"
alias ghist="history | grep"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Quicklook
alias ql='qlmanage -p "$@" >& /dev/null'

# Get readable list of network IPs
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print \$1'"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"

# https://github.com/nvbn/thefuck
# alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'

alias t="tmuxinator"
alias g="git"
alias e="ember"
alias a="atom"


man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}
